[package]
edition = "2024"
license = "Apache-2.0"
name    = "blob-stream-broker-discovery"
publish = false
version = "0.1.0"

[lib]
doctest = true

[dependencies]
anyhow.workspace       = true
async-trait.workspace  = true
bd-log.workspace       = true
bd-log-util.workspace  = true
blob-stream-proto.path = "../blob-stream-proto"
futures.workspace      = true
k8s-openapi.workspace  = true
kube.workspace         = true
log.workspace          = true
protobuf.workspace     = true
time.workspace         = true
tokio.workspace        = true
tokio-stream.workspace = true

[dev-dependencies]
mockall.workspace = true
