[workspace]
members = [
	"blob-stream-broker-discovery",
	"blob-stream-broker",
	"blob-stream-blob-store",
	"blob-stream-metadata-store",
	"blob-stream-consumer",
	"blob-stream-integration-tests",
	"blob-stream-producer",
	"blob-stream-proto",
	"blob-stream-types",
]
resolver = "2"

[workspace.dependencies]
anyhow            = "1.0.103"
async-trait       = "0.1.89"
aws-config        = "1.9.0"
aws-sdk-dynamodb  = "1.117.0"
aws-sdk-s3        = "1.138.0"
aws-types         = "1.4.0"
axum              = { version = "0.8.9", features = ["http2", "macros"] }
bd-grpc           = { git = "https://github.com/bitdriftlabs/shared-core.git" }
bd-log            = { git = "https://github.com/bitdriftlabs/shared-core.git" }
bd-panic          = { git = "https://github.com/bitdriftlabs/shared-core.git" }
bd-pgv            = { git = "https://github.com/bitdriftlabs/shared-core.git" }
bd-rt             = { git = "https://github.com/bitdriftlabs/shared-core.git" }
bd-runtime-config = { git = "https://github.com/bitdriftlabs/shared-core.git" }
bd-server-stats   = { git = "https://github.com/bitdriftlabs/shared-core.git" }
bd-test-helpers   = { git = "https://github.com/bitdriftlabs/shared-core.git" }
bd-time           = { git = "https://github.com/bitdriftlabs/shared-core.git" }
bytes             = "1.12.1"
clap              = { version = "4.6.2", features = ["derive", "env"] }
ctor              = "1.0.9"
futures           = "0.3.32"
hostname          = "0.4.2"
http              = "1.4.2"
hyper-util        = { version = "0.1.20", features = ["client", "client-legacy"] }
k8s-openapi       = { version = "0.28.0", features = ["v1_32"] }
kube              = { version = "4.0.0", features = ["runtime", "rustls-tls"], default-features = false }
log               = "0.4.33"
mockall           = "0.15.0"
parking_lot       = "0.12.5"
prometheus        = "0.14.0"

protobuf = { git = "https://github.com/bitdriftlabs/rust-protobuf.git", branch = "patch-stack", features = [
	"with-bytes",
] }
protobuf-codegen = { git = "https://github.com/bitdriftlabs/rust-protobuf.git", branch = "patch-stack" }
protobuf-json-mapping = { git = "https://github.com/bitdriftlabs/rust-protobuf.git", branch = "patch-stack" }

serde             = { version = "1.0.228", features = ["derive"] }
serde_dynamo      = "4.3.0"
serde_json        = { version = "1.0.150" }
serde_yaml        = "0.9.34"
sonyflake         = { git = "https://github.com/mattklein123/sonyflake-rs.git" }
thiserror         = "2.0.18"
tikv-jemallocator = "0.7.0"
time              = { version = "0.3.53", features = ["formatting", "serde-well-known", "macros", "parsing"] }
tokio             = { version = "1.52.4", features = ["full"] }
tokio-stream      = "0.1.18"
uuid              = { version = "1.24.0", features = ["v4"] }
zstd              = "0.13.3"
