name: blob-stream

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: blob-stream-dynamodb-local
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    ports:
      - "8000:8000"

  localstack:
    image: localstack/localstack:4.14.0
    container_name: blob-stream-localstack
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
