[package]
edition = "2024"
name    = "blob-stream-consumer"
publish = false
version = "0.1.0"

[lib]
doctest = true

[features]
admin = ["dep:axum"]

[dependencies]
anyhow.workspace                = true
async-trait.workspace           = true
axum                            = { workspace = true, optional = true }
aws-config.workspace            = true
aws-sdk-dynamodb.workspace      = true
aws-sdk-s3.workspace            = true
aws-types.workspace             = true
bd-log.workspace                = true
bd-pgv.workspace                = true
bd-server-stats.workspace       = true
blob-stream-blob-store.path     = "../blob-stream-blob-store"
blob-stream-metadata-store.path = "../blob-stream-metadata-store"
blob-stream-proto.path          = "../blob-stream-proto"
blob-stream-types.path          = "../blob-stream-types"
futures.workspace               = true
log.workspace                   = true
prometheus.workspace            = true
protobuf.workspace              = true
serde_json.workspace            = true
serde.workspace                 = true
time.workspace                  = true
tokio.workspace                 = true
zstd.workspace                  = true

[dev-dependencies]
bytes.workspace = true
