[package]
edition = "2024"
license = "Apache-2.0"
name    = "blob-stream-consumer"
publish = false
version = "0.1.0"

[lib]
doctest = true

[dependencies]
anyhow.workspace                  = true
async-trait.workspace             = true
aws-config.workspace              = true
aws-sdk-dynamodb.workspace        = true
aws-sdk-s3.workspace              = true
aws-types.workspace               = true
axum.workspace                    = true
bd-backoff.workspace              = true
bd-grpc.workspace                 = true
bd-log.workspace                  = true
bd-log-util.workspace             = true
bd-pgv.workspace                  = true
bd-runtime-config.workspace       = true
bd-server-stats.workspace         = true
bd-time.workspace                 = true
blob-stream-blob-store.path       = "../blob-stream-blob-store"
blob-stream-broker-discovery.path = "../blob-stream-broker-discovery"
blob-stream-metadata-store.path   = "../blob-stream-metadata-store"
blob-stream-proto.path            = "../blob-stream-proto"
blob-stream-runtime-config.path   = "../blob-stream-runtime-config"
blob-stream-types.path            = "../blob-stream-types"
bytes.workspace                   = true
futures.workspace                 = true
hyper-util.workspace              = true
log.workspace                     = true
parking_lot.workspace             = true
prometheus.workspace              = true
protobuf.workspace                = true
serde.workspace                   = true
serde_json.workspace              = true
time.workspace                    = true
tokio.workspace                   = true
tracing.workspace                 = true
uuid.workspace                    = true
zstd.workspace                    = true

[dev-dependencies]
bd-test-helpers-core.workspace = true
blob-stream-test-utils.path    = "../blob-stream-test-utils"
