[package]
edition = "2024"
name    = "blob-stream-producer"
publish = false
version = "0.1.0"

[lib]
doctest = true

[dependencies]
anyhow.workspace                  = true
async-trait.workspace             = true
axum.workspace                    = true
bd-backoff.workspace              = true
bd-grpc.workspace                 = true
bd-log.workspace                  = true
bd-pgv.workspace                  = true
bd-server-stats.workspace         = true
blob-stream-broker-discovery.path = "../blob-stream-broker-discovery"
blob-stream-proto.path            = "../blob-stream-proto"
blob-stream-types.path            = "../blob-stream-types"
bytes.workspace                    = true
futures.workspace                 = true
hyper-util.workspace              = true
log.workspace                     = true
parking_lot.workspace             = true
prometheus.workspace              = true
protobuf.workspace                = true
serde.workspace                   = true
thiserror.workspace               = true
time.workspace                    = true
tokio.workspace                   = true
