
// This file is generated by rust-protobuf 4.0.0-alpha.0. Do not edit
// .proto file is parsed by protoc 35.1
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `blobstream/v1/broker.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_4_0_0_ALPHA_0;

// @@protoc_insertion_point(message:blobstream.v1.Record)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Record {
    // message fields
    // @@protoc_insertion_point(field:blobstream.v1.Record.payload)
    pub payload: ::bytes::Bytes,
    // @@protoc_insertion_point(field:blobstream.v1.Record.event_ts_ms)
    pub event_ts_ms: i64,
    // special fields
    // @@protoc_insertion_point(special_field:blobstream.v1.Record.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Record {
    fn default() -> &'a Record {
        <Record as ::protobuf::Message>::default_instance()
    }
}

impl Record {
    pub fn new() -> Record {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "payload",
            |m: &Record| { &m.payload },
            |m: &mut Record| { &mut m.payload },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "event_ts_ms",
            |m: &Record| { &m.event_ts_ms },
            |m: &mut Record| { &mut m.event_ts_ms },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Record>(
            "Record",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Record {
    const NAME: &'static str = "Record";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.payload = is.read_tokio_bytes()?;
                },
                16 => {
                    self.event_ts_ms = is.read_int64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.payload.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.payload);
        }
        if self.event_ts_ms != 0 {
            my_size += ::protobuf::rt::int64_size(2, self.event_ts_ms);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.payload.is_empty() {
            os.write_bytes(1, &self.payload)?;
        }
        if self.event_ts_ms != 0 {
            os.write_int64(2, self.event_ts_ms)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Record {
        Record::new()
    }

    fn clear(&mut self) {
        self.payload.clear();
        self.event_ts_ms = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Record {
        static instance: Record = Record {
            payload: ::bytes::Bytes::new(),
            event_ts_ms: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Record {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Record").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Record {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Record {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:blobstream.v1.StoredRecordBatch)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct StoredRecordBatch {
    // message fields
    // @@protoc_insertion_point(field:blobstream.v1.StoredRecordBatch.virtual_partition_id)
    pub virtual_partition_id: u32,
    // @@protoc_insertion_point(field:blobstream.v1.StoredRecordBatch.records)
    pub records: ::std::vec::Vec<Record>,
    // special fields
    // @@protoc_insertion_point(special_field:blobstream.v1.StoredRecordBatch.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a StoredRecordBatch {
    fn default() -> &'a StoredRecordBatch {
        <StoredRecordBatch as ::protobuf::Message>::default_instance()
    }
}

impl StoredRecordBatch {
    pub fn new() -> StoredRecordBatch {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "virtual_partition_id",
            |m: &StoredRecordBatch| { &m.virtual_partition_id },
            |m: &mut StoredRecordBatch| { &mut m.virtual_partition_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "records",
            |m: &StoredRecordBatch| { &m.records },
            |m: &mut StoredRecordBatch| { &mut m.records },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<StoredRecordBatch>(
            "StoredRecordBatch",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for StoredRecordBatch {
    const NAME: &'static str = "StoredRecordBatch";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.virtual_partition_id = is.read_uint32()?;
                },
                18 => {
                    self.records.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.virtual_partition_id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.virtual_partition_id);
        }
        for value in &self.records {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.virtual_partition_id != 0 {
            os.write_uint32(1, self.virtual_partition_id)?;
        }
        for v in &self.records {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> StoredRecordBatch {
        StoredRecordBatch::new()
    }

    fn clear(&mut self) {
        self.virtual_partition_id = 0;
        self.records.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static StoredRecordBatch {
        static instance: StoredRecordBatch = StoredRecordBatch {
            virtual_partition_id: 0,
            records: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for StoredRecordBatch {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("StoredRecordBatch").unwrap()).clone()
    }
}

impl ::std::fmt::Display for StoredRecordBatch {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for StoredRecordBatch {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:blobstream.v1.ProduceBatchRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ProduceBatchRequest {
    // message fields
    // @@protoc_insertion_point(field:blobstream.v1.ProduceBatchRequest.topic)
    pub topic: ::protobuf::Chars,
    // @@protoc_insertion_point(field:blobstream.v1.ProduceBatchRequest.virtual_partition_id)
    pub virtual_partition_id: u32,
    // @@protoc_insertion_point(field:blobstream.v1.ProduceBatchRequest.records)
    pub records: ::std::vec::Vec<Record>,
    // special fields
    // @@protoc_insertion_point(special_field:blobstream.v1.ProduceBatchRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ProduceBatchRequest {
    fn default() -> &'a ProduceBatchRequest {
        <ProduceBatchRequest as ::protobuf::Message>::default_instance()
    }
}

impl ProduceBatchRequest {
    pub fn new() -> ProduceBatchRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "topic",
            |m: &ProduceBatchRequest| { &m.topic },
            |m: &mut ProduceBatchRequest| { &mut m.topic },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "virtual_partition_id",
            |m: &ProduceBatchRequest| { &m.virtual_partition_id },
            |m: &mut ProduceBatchRequest| { &mut m.virtual_partition_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "records",
            |m: &ProduceBatchRequest| { &m.records },
            |m: &mut ProduceBatchRequest| { &mut m.records },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ProduceBatchRequest>(
            "ProduceBatchRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ProduceBatchRequest {
    const NAME: &'static str = "ProduceBatchRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.topic = is.read_tokio_chars()?;
                },
                16 => {
                    self.virtual_partition_id = is.read_uint32()?;
                },
                26 => {
                    self.records.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.topic.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.topic);
        }
        if self.virtual_partition_id != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.virtual_partition_id);
        }
        for value in &self.records {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.topic.is_empty() {
            os.write_string(1, &self.topic)?;
        }
        if self.virtual_partition_id != 0 {
            os.write_uint32(2, self.virtual_partition_id)?;
        }
        for v in &self.records {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ProduceBatchRequest {
        ProduceBatchRequest::new()
    }

    fn clear(&mut self) {
        self.topic.clear();
        self.virtual_partition_id = 0;
        self.records.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ProduceBatchRequest {
        static instance: ProduceBatchRequest = ProduceBatchRequest {
            topic: ::protobuf::Chars::new(),
            virtual_partition_id: 0,
            records: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ProduceBatchRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ProduceBatchRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ProduceBatchRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProduceBatchRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:blobstream.v1.ProduceBatchResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ProduceBatchResponse {
    // message fields
    // @@protoc_insertion_point(field:blobstream.v1.ProduceBatchResponse.status)
    pub status: ::protobuf::EnumOrUnknown<ProduceStatus>,
    // @@protoc_insertion_point(field:blobstream.v1.ProduceBatchResponse.error_message)
    pub error_message: ::protobuf::Chars,
    // special fields
    // @@protoc_insertion_point(special_field:blobstream.v1.ProduceBatchResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ProduceBatchResponse {
    fn default() -> &'a ProduceBatchResponse {
        <ProduceBatchResponse as ::protobuf::Message>::default_instance()
    }
}

impl ProduceBatchResponse {
    pub fn new() -> ProduceBatchResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "status",
            |m: &ProduceBatchResponse| { &m.status },
            |m: &mut ProduceBatchResponse| { &mut m.status },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "error_message",
            |m: &ProduceBatchResponse| { &m.error_message },
            |m: &mut ProduceBatchResponse| { &mut m.error_message },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ProduceBatchResponse>(
            "ProduceBatchResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ProduceBatchResponse {
    const NAME: &'static str = "ProduceBatchResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.status = is.read_enum_or_unknown()?;
                },
                18 => {
                    self.error_message = is.read_tokio_chars()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.status != ::protobuf::EnumOrUnknown::new(ProduceStatus::PRODUCE_STATUS_OK) {
            my_size += ::protobuf::rt::int32_size(1, self.status.value());
        }
        if !self.error_message.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.error_message);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.status != ::protobuf::EnumOrUnknown::new(ProduceStatus::PRODUCE_STATUS_OK) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.status))?;
        }
        if !self.error_message.is_empty() {
            os.write_string(2, &self.error_message)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ProduceBatchResponse {
        ProduceBatchResponse::new()
    }

    fn clear(&mut self) {
        self.status = ::protobuf::EnumOrUnknown::new(ProduceStatus::PRODUCE_STATUS_OK);
        self.error_message.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ProduceBatchResponse {
        static instance: ProduceBatchResponse = ProduceBatchResponse {
            status: ::protobuf::EnumOrUnknown::from_i32(0),
            error_message: ::protobuf::Chars::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ProduceBatchResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ProduceBatchResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ProduceBatchResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProduceBatchResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:blobstream.v1.ProduceBatchesRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ProduceBatchesRequest {
    // message fields
    // @@protoc_insertion_point(field:blobstream.v1.ProduceBatchesRequest.batches)
    pub batches: ::std::vec::Vec<ProduceBatchRequest>,
    // special fields
    // @@protoc_insertion_point(special_field:blobstream.v1.ProduceBatchesRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ProduceBatchesRequest {
    fn default() -> &'a ProduceBatchesRequest {
        <ProduceBatchesRequest as ::protobuf::Message>::default_instance()
    }
}

impl ProduceBatchesRequest {
    pub fn new() -> ProduceBatchesRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "batches",
            |m: &ProduceBatchesRequest| { &m.batches },
            |m: &mut ProduceBatchesRequest| { &mut m.batches },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ProduceBatchesRequest>(
            "ProduceBatchesRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ProduceBatchesRequest {
    const NAME: &'static str = "ProduceBatchesRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.batches.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.batches {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.batches {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ProduceBatchesRequest {
        ProduceBatchesRequest::new()
    }

    fn clear(&mut self) {
        self.batches.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ProduceBatchesRequest {
        static instance: ProduceBatchesRequest = ProduceBatchesRequest {
            batches: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ProduceBatchesRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ProduceBatchesRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ProduceBatchesRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProduceBatchesRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:blobstream.v1.ProduceBatchesResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ProduceBatchesResponse {
    // message fields
    // @@protoc_insertion_point(field:blobstream.v1.ProduceBatchesResponse.results)
    pub results: ::std::vec::Vec<ProduceBatchResponse>,
    // special fields
    // @@protoc_insertion_point(special_field:blobstream.v1.ProduceBatchesResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ProduceBatchesResponse {
    fn default() -> &'a ProduceBatchesResponse {
        <ProduceBatchesResponse as ::protobuf::Message>::default_instance()
    }
}

impl ProduceBatchesResponse {
    pub fn new() -> ProduceBatchesResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "results",
            |m: &ProduceBatchesResponse| { &m.results },
            |m: &mut ProduceBatchesResponse| { &mut m.results },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ProduceBatchesResponse>(
            "ProduceBatchesResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ProduceBatchesResponse {
    const NAME: &'static str = "ProduceBatchesResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.results.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.results {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.results {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ProduceBatchesResponse {
        ProduceBatchesResponse::new()
    }

    fn clear(&mut self) {
        self.results.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ProduceBatchesResponse {
        static instance: ProduceBatchesResponse = ProduceBatchesResponse {
            results: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ProduceBatchesResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ProduceBatchesResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ProduceBatchesResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProduceBatchesResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:blobstream.v1.ProduceStatus)
pub enum ProduceStatus {
    // @@protoc_insertion_point(enum_value:blobstream.v1.ProduceStatus.PRODUCE_STATUS_OK)
    PRODUCE_STATUS_OK = 0,
    // @@protoc_insertion_point(enum_value:blobstream.v1.ProduceStatus.PRODUCE_STATUS_NOT_LEASE_HOLDER)
    PRODUCE_STATUS_NOT_LEASE_HOLDER = 1,
    // @@protoc_insertion_point(enum_value:blobstream.v1.ProduceStatus.PRODUCE_STATUS_UNKNOWN_TOPIC)
    PRODUCE_STATUS_UNKNOWN_TOPIC = 2,
    // @@protoc_insertion_point(enum_value:blobstream.v1.ProduceStatus.PRODUCE_STATUS_OVERLOADED)
    PRODUCE_STATUS_OVERLOADED = 3,
}

impl ::protobuf::Enum for ProduceStatus {
    const NAME: &'static str = "ProduceStatus";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ProduceStatus> {
        match value {
            0 => ::std::option::Option::Some(ProduceStatus::PRODUCE_STATUS_OK),
            1 => ::std::option::Option::Some(ProduceStatus::PRODUCE_STATUS_NOT_LEASE_HOLDER),
            2 => ::std::option::Option::Some(ProduceStatus::PRODUCE_STATUS_UNKNOWN_TOPIC),
            3 => ::std::option::Option::Some(ProduceStatus::PRODUCE_STATUS_OVERLOADED),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<ProduceStatus> {
        match str {
            "PRODUCE_STATUS_OK" => ::std::option::Option::Some(ProduceStatus::PRODUCE_STATUS_OK),
            "PRODUCE_STATUS_NOT_LEASE_HOLDER" => ::std::option::Option::Some(ProduceStatus::PRODUCE_STATUS_NOT_LEASE_HOLDER),
            "PRODUCE_STATUS_UNKNOWN_TOPIC" => ::std::option::Option::Some(ProduceStatus::PRODUCE_STATUS_UNKNOWN_TOPIC),
            "PRODUCE_STATUS_OVERLOADED" => ::std::option::Option::Some(ProduceStatus::PRODUCE_STATUS_OVERLOADED),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [ProduceStatus] = &[
        ProduceStatus::PRODUCE_STATUS_OK,
        ProduceStatus::PRODUCE_STATUS_NOT_LEASE_HOLDER,
        ProduceStatus::PRODUCE_STATUS_UNKNOWN_TOPIC,
        ProduceStatus::PRODUCE_STATUS_OVERLOADED,
    ];
}

impl ::protobuf::EnumFull for ProduceStatus {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("ProduceStatus").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for ProduceStatus {
    fn default() -> Self {
        ProduceStatus::PRODUCE_STATUS_OK
    }
}

impl ProduceStatus {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<ProduceStatus>("ProduceStatus")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1ablobstream/v1/broker.proto\x12\rblobstream.v1\"B\n\x06Record\x12\
    \x18\n\x07payload\x18\x01\x20\x01(\x0cR\x07payload\x12\x1e\n\x0bevent_ts\
    _ms\x18\x02\x20\x01(\x03R\teventTsMs\"v\n\x11StoredRecordBatch\x120\n\
    \x14virtual_partition_id\x18\x01\x20\x01(\rR\x12virtualPartitionId\x12/\
    \n\x07records\x18\x02\x20\x03(\x0b2\x15.blobstream.v1.RecordR\x07records\
    \"\x8e\x01\n\x13ProduceBatchRequest\x12\x14\n\x05topic\x18\x01\x20\x01(\
    \tR\x05topic\x120\n\x14virtual_partition_id\x18\x02\x20\x01(\rR\x12virtu\
    alPartitionId\x12/\n\x07records\x18\x03\x20\x03(\x0b2\x15.blobstream.v1.\
    RecordR\x07records\"q\n\x14ProduceBatchResponse\x124\n\x06status\x18\x01\
    \x20\x01(\x0e2\x1c.blobstream.v1.ProduceStatusR\x06status\x12#\n\rerror_\
    message\x18\x02\x20\x01(\tR\x0cerrorMessage\"U\n\x15ProduceBatchesReques\
    t\x12<\n\x07batches\x18\x01\x20\x03(\x0b2\".blobstream.v1.ProduceBatchRe\
    questR\x07batches\"W\n\x16ProduceBatchesResponse\x12=\n\x07results\x18\
    \x01\x20\x03(\x0b2#.blobstream.v1.ProduceBatchResponseR\x07results*\x8c\
    \x01\n\rProduceStatus\x12\x15\n\x11PRODUCE_STATUS_OK\x10\0\x12#\n\x1fPRO\
    DUCE_STATUS_NOT_LEASE_HOLDER\x10\x01\x12\x20\n\x1cPRODUCE_STATUS_UNKNOWN\
    _TOPIC\x10\x02\x12\x1d\n\x19PRODUCE_STATUS_OVERLOADED\x10\x032\xc7\x01\n\
    \rBrokerService\x12W\n\x0cProduceBatch\x12\".blobstream.v1.ProduceBatchR\
    equest\x1a#.blobstream.v1.ProduceBatchResponse\x12]\n\x0eProduceBatches\
    \x12$.blobstream.v1.ProduceBatchesRequest\x1a%.blobstream.v1.ProduceBatc\
    hesResponseb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(6);
            messages.push(Record::generated_message_descriptor_data());
            messages.push(StoredRecordBatch::generated_message_descriptor_data());
            messages.push(ProduceBatchRequest::generated_message_descriptor_data());
            messages.push(ProduceBatchResponse::generated_message_descriptor_data());
            messages.push(ProduceBatchesRequest::generated_message_descriptor_data());
            messages.push(ProduceBatchesResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(ProduceStatus::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
