// proto - blob-stream API definitions
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// This file is generated by rust-protobuf 4.0.0-alpha.0. Do not edit
// .proto file is parsed by protoc 33.2
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `blobstream/v1/config.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_4_0_0_ALPHA_0;

// @@protoc_insertion_point(message:blobstream.v1.BrokerConfig)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct BrokerConfig {
    // message fields
    // @@protoc_insertion_point(field:blobstream.v1.BrokerConfig.flush_max_bytes)
    pub flush_max_bytes: u32,
    // @@protoc_insertion_point(field:blobstream.v1.BrokerConfig.flush_max_delay_ms)
    pub flush_max_delay_ms: u32,
    // @@protoc_insertion_point(field:blobstream.v1.BrokerConfig.bind_addr)
    pub bind_addr: ::protobuf::Chars,
    // special fields
    // @@protoc_insertion_point(special_field:blobstream.v1.BrokerConfig.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a BrokerConfig {
    fn default() -> &'a BrokerConfig {
        <BrokerConfig as ::protobuf::Message>::default_instance()
    }
}

impl BrokerConfig {
    pub fn new() -> BrokerConfig {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "flush_max_bytes",
            |m: &BrokerConfig| { &m.flush_max_bytes },
            |m: &mut BrokerConfig| { &mut m.flush_max_bytes },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "flush_max_delay_ms",
            |m: &BrokerConfig| { &m.flush_max_delay_ms },
            |m: &mut BrokerConfig| { &mut m.flush_max_delay_ms },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "bind_addr",
            |m: &BrokerConfig| { &m.bind_addr },
            |m: &mut BrokerConfig| { &mut m.bind_addr },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<BrokerConfig>(
            "BrokerConfig",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for BrokerConfig {
    const NAME: &'static str = "BrokerConfig";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.flush_max_bytes = is.read_uint32()?;
                },
                16 => {
                    self.flush_max_delay_ms = is.read_uint32()?;
                },
                26 => {
                    self.bind_addr = is.read_tokio_chars()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.flush_max_bytes != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.flush_max_bytes);
        }
        if self.flush_max_delay_ms != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.flush_max_delay_ms);
        }
        if !self.bind_addr.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.bind_addr);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.flush_max_bytes != 0 {
            os.write_uint32(1, self.flush_max_bytes)?;
        }
        if self.flush_max_delay_ms != 0 {
            os.write_uint32(2, self.flush_max_delay_ms)?;
        }
        if !self.bind_addr.is_empty() {
            os.write_string(3, &self.bind_addr)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> BrokerConfig {
        BrokerConfig::new()
    }

    fn clear(&mut self) {
        self.flush_max_bytes = 0;
        self.flush_max_delay_ms = 0;
        self.bind_addr.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static BrokerConfig {
        static instance: BrokerConfig = BrokerConfig {
            flush_max_bytes: 0,
            flush_max_delay_ms: 0,
            bind_addr: ::protobuf::Chars::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for BrokerConfig {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("BrokerConfig").unwrap()).clone()
    }
}

impl ::std::fmt::Display for BrokerConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BrokerConfig {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:blobstream.v1.TopicConfig)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TopicConfig {
    // message fields
    // @@protoc_insertion_point(field:blobstream.v1.TopicConfig.name)
    pub name: ::protobuf::Chars,
    // @@protoc_insertion_point(field:blobstream.v1.TopicConfig.partition_count)
    pub partition_count: u32,
    // @@protoc_insertion_point(field:blobstream.v1.TopicConfig.num_writers)
    pub num_writers: u32,
    // @@protoc_insertion_point(field:blobstream.v1.TopicConfig.retention_days)
    pub retention_days: u32,
    // special fields
    // @@protoc_insertion_point(special_field:blobstream.v1.TopicConfig.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TopicConfig {
    fn default() -> &'a TopicConfig {
        <TopicConfig as ::protobuf::Message>::default_instance()
    }
}

impl TopicConfig {
    pub fn new() -> TopicConfig {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &TopicConfig| { &m.name },
            |m: &mut TopicConfig| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "partition_count",
            |m: &TopicConfig| { &m.partition_count },
            |m: &mut TopicConfig| { &mut m.partition_count },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "num_writers",
            |m: &TopicConfig| { &m.num_writers },
            |m: &mut TopicConfig| { &mut m.num_writers },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "retention_days",
            |m: &TopicConfig| { &m.retention_days },
            |m: &mut TopicConfig| { &mut m.retention_days },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TopicConfig>(
            "TopicConfig",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TopicConfig {
    const NAME: &'static str = "TopicConfig";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_tokio_chars()?;
                },
                16 => {
                    self.partition_count = is.read_uint32()?;
                },
                24 => {
                    self.num_writers = is.read_uint32()?;
                },
                32 => {
                    self.retention_days = is.read_uint32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if self.partition_count != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.partition_count);
        }
        if self.num_writers != 0 {
            my_size += ::protobuf::rt::uint32_size(3, self.num_writers);
        }
        if self.retention_days != 0 {
            my_size += ::protobuf::rt::uint32_size(4, self.retention_days);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if self.partition_count != 0 {
            os.write_uint32(2, self.partition_count)?;
        }
        if self.num_writers != 0 {
            os.write_uint32(3, self.num_writers)?;
        }
        if self.retention_days != 0 {
            os.write_uint32(4, self.retention_days)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TopicConfig {
        TopicConfig::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.partition_count = 0;
        self.num_writers = 0;
        self.retention_days = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TopicConfig {
        static instance: TopicConfig = TopicConfig {
            name: ::protobuf::Chars::new(),
            partition_count: 0,
            num_writers: 0,
            retention_days: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TopicConfig {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TopicConfig").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TopicConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TopicConfig {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:blobstream.v1.RuntimeConfig)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RuntimeConfig {
    // message fields
    // @@protoc_insertion_point(field:blobstream.v1.RuntimeConfig.broker)
    pub broker: ::protobuf::MessageField<BrokerConfig>,
    // @@protoc_insertion_point(field:blobstream.v1.RuntimeConfig.topics)
    pub topics: ::std::vec::Vec<TopicConfig>,
    // special fields
    // @@protoc_insertion_point(special_field:blobstream.v1.RuntimeConfig.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RuntimeConfig {
    fn default() -> &'a RuntimeConfig {
        <RuntimeConfig as ::protobuf::Message>::default_instance()
    }
}

impl RuntimeConfig {
    pub fn new() -> RuntimeConfig {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, BrokerConfig>(
            "broker",
            |m: &RuntimeConfig| { &m.broker },
            |m: &mut RuntimeConfig| { &mut m.broker },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "topics",
            |m: &RuntimeConfig| { &m.topics },
            |m: &mut RuntimeConfig| { &mut m.topics },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RuntimeConfig>(
            "RuntimeConfig",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RuntimeConfig {
    const NAME: &'static str = "RuntimeConfig";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.broker)?;
                },
                18 => {
                    self.topics.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.broker.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.topics {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.broker.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        for v in &self.topics {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RuntimeConfig {
        RuntimeConfig::new()
    }

    fn clear(&mut self) {
        self.broker.clear();
        self.topics.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RuntimeConfig {
        static instance: RuntimeConfig = RuntimeConfig {
            broker: ::protobuf::MessageField::none(),
            topics: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RuntimeConfig {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RuntimeConfig").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RuntimeConfig {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RuntimeConfig {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1ablobstream/v1/config.proto\x12\rblobstream.v1\"\x80\x01\n\x0cBroke\
    rConfig\x12&\n\x0fflush_max_bytes\x18\x01\x20\x01(\rR\rflushMaxBytes\x12\
    +\n\x12flush_max_delay_ms\x18\x02\x20\x01(\rR\x0fflushMaxDelayMs\x12\x1b\
    \n\tbind_addr\x18\x03\x20\x01(\tR\x08bindAddr\"\x92\x01\n\x0bTopicConfig\
    \x12\x12\n\x04name\x18\x01\x20\x01(\tR\x04name\x12'\n\x0fpartition_count\
    \x18\x02\x20\x01(\rR\x0epartitionCount\x12\x1f\n\x0bnum_writers\x18\x03\
    \x20\x01(\rR\nnumWriters\x12%\n\x0eretention_days\x18\x04\x20\x01(\rR\rr\
    etentionDays\"x\n\rRuntimeConfig\x123\n\x06broker\x18\x01\x20\x01(\x0b2\
    \x1b.blobstream.v1.BrokerConfigR\x06broker\x122\n\x06topics\x18\x02\x20\
    \x03(\x0b2\x1a.blobstream.v1.TopicConfigR\x06topicsb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(BrokerConfig::generated_message_descriptor_data());
            messages.push(TopicConfig::generated_message_descriptor_data());
            messages.push(RuntimeConfig::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
