
// This file is generated by rust-protobuf 4.0.0-alpha.0. Do not edit
// .proto file is parsed by protoc 36.2
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `blobstream/v1/metadata.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_4_0_0_ALPHA_0;

// @@protoc_insertion_point(message:blobstream.v1.SegmentMetadataV1)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SegmentMetadataV1 {
    // message fields
    // @@protoc_insertion_point(field:blobstream.v1.SegmentMetadataV1.blob_key)
    pub blob_key: ::protobuf::Chars,
    // @@protoc_insertion_point(field:blobstream.v1.SegmentMetadataV1.created_ts_ms)
    pub created_ts_ms: i64,
    // @@protoc_insertion_point(field:blobstream.v1.SegmentMetadataV1.metadata_published_ts_ms)
    pub metadata_published_ts_ms: i64,
    // @@protoc_insertion_point(field:blobstream.v1.SegmentMetadataV1.compression)
    pub compression: ::protobuf::MessageField<StoredSegmentCompression>,
    // @@protoc_insertion_point(field:blobstream.v1.SegmentMetadataV1.partitions)
    pub partitions: ::std::vec::Vec<SegmentPartitionIndex>,
    // special fields
    // @@protoc_insertion_point(special_field:blobstream.v1.SegmentMetadataV1.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SegmentMetadataV1 {
    fn default() -> &'a SegmentMetadataV1 {
        <SegmentMetadataV1 as ::protobuf::Message>::default_instance()
    }
}

impl SegmentMetadataV1 {
    pub fn new() -> SegmentMetadataV1 {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "blob_key",
            |m: &SegmentMetadataV1| { &m.blob_key },
            |m: &mut SegmentMetadataV1| { &mut m.blob_key },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "created_ts_ms",
            |m: &SegmentMetadataV1| { &m.created_ts_ms },
            |m: &mut SegmentMetadataV1| { &mut m.created_ts_ms },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "metadata_published_ts_ms",
            |m: &SegmentMetadataV1| { &m.metadata_published_ts_ms },
            |m: &mut SegmentMetadataV1| { &mut m.metadata_published_ts_ms },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, StoredSegmentCompression>(
            "compression",
            |m: &SegmentMetadataV1| { &m.compression },
            |m: &mut SegmentMetadataV1| { &mut m.compression },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "partitions",
            |m: &SegmentMetadataV1| { &m.partitions },
            |m: &mut SegmentMetadataV1| { &mut m.partitions },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SegmentMetadataV1>(
            "SegmentMetadataV1",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SegmentMetadataV1 {
    const NAME: &'static str = "SegmentMetadataV1";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.blob_key = is.read_tokio_chars()?;
                },
                16 => {
                    self.created_ts_ms = is.read_int64()?;
                },
                24 => {
                    self.metadata_published_ts_ms = is.read_int64()?;
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.compression)?;
                },
                42 => {
                    self.partitions.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.blob_key.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.blob_key);
        }
        if self.created_ts_ms != 0 {
            my_size += ::protobuf::rt::int64_size(2, self.created_ts_ms);
        }
        if self.metadata_published_ts_ms != 0 {
            my_size += ::protobuf::rt::int64_size(3, self.metadata_published_ts_ms);
        }
        if let Some(v) = self.compression.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.partitions {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.blob_key.is_empty() {
            os.write_string(1, &self.blob_key)?;
        }
        if self.created_ts_ms != 0 {
            os.write_int64(2, self.created_ts_ms)?;
        }
        if self.metadata_published_ts_ms != 0 {
            os.write_int64(3, self.metadata_published_ts_ms)?;
        }
        if let Some(v) = self.compression.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        for v in &self.partitions {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SegmentMetadataV1 {
        SegmentMetadataV1::new()
    }

    fn clear(&mut self) {
        self.blob_key.clear();
        self.created_ts_ms = 0;
        self.metadata_published_ts_ms = 0;
        self.compression.clear();
        self.partitions.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SegmentMetadataV1 {
        static instance: SegmentMetadataV1 = SegmentMetadataV1 {
            blob_key: ::protobuf::Chars::new(),
            created_ts_ms: 0,
            metadata_published_ts_ms: 0,
            compression: ::protobuf::MessageField::none(),
            partitions: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SegmentMetadataV1 {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SegmentMetadataV1").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SegmentMetadataV1 {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SegmentMetadataV1 {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:blobstream.v1.StoredSegmentCompression)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct StoredSegmentCompression {
    // message fields
    // @@protoc_insertion_point(field:blobstream.v1.StoredSegmentCompression.codec)
    pub codec: ::protobuf::EnumOrUnknown<StoredSegmentCompressionCodec>,
    // @@protoc_insertion_point(field:blobstream.v1.StoredSegmentCompression.level)
    pub level: i32,
    // special fields
    // @@protoc_insertion_point(special_field:blobstream.v1.StoredSegmentCompression.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a StoredSegmentCompression {
    fn default() -> &'a StoredSegmentCompression {
        <StoredSegmentCompression as ::protobuf::Message>::default_instance()
    }
}

impl StoredSegmentCompression {
    pub fn new() -> StoredSegmentCompression {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "codec",
            |m: &StoredSegmentCompression| { &m.codec },
            |m: &mut StoredSegmentCompression| { &mut m.codec },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "level",
            |m: &StoredSegmentCompression| { &m.level },
            |m: &mut StoredSegmentCompression| { &mut m.level },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<StoredSegmentCompression>(
            "StoredSegmentCompression",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for StoredSegmentCompression {
    const NAME: &'static str = "StoredSegmentCompression";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.codec = is.read_enum_or_unknown()?;
                },
                16 => {
                    self.level = is.read_int32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.codec != ::protobuf::EnumOrUnknown::new(StoredSegmentCompressionCodec::STORED_SEGMENT_COMPRESSION_CODEC_NONE) {
            my_size += ::protobuf::rt::int32_size(1, self.codec.value());
        }
        if self.level != 0 {
            my_size += ::protobuf::rt::int32_size(2, self.level);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.codec != ::protobuf::EnumOrUnknown::new(StoredSegmentCompressionCodec::STORED_SEGMENT_COMPRESSION_CODEC_NONE) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.codec))?;
        }
        if self.level != 0 {
            os.write_int32(2, self.level)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> StoredSegmentCompression {
        StoredSegmentCompression::new()
    }

    fn clear(&mut self) {
        self.codec = ::protobuf::EnumOrUnknown::new(StoredSegmentCompressionCodec::STORED_SEGMENT_COMPRESSION_CODEC_NONE);
        self.level = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static StoredSegmentCompression {
        static instance: StoredSegmentCompression = StoredSegmentCompression {
            codec: ::protobuf::EnumOrUnknown::from_i32(0),
            level: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for StoredSegmentCompression {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("StoredSegmentCompression").unwrap()).clone()
    }
}

impl ::std::fmt::Display for StoredSegmentCompression {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for StoredSegmentCompression {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:blobstream.v1.SegmentPartitionIndex)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SegmentPartitionIndex {
    // message fields
    // @@protoc_insertion_point(field:blobstream.v1.SegmentPartitionIndex.virtual_partition_id)
    pub virtual_partition_id: u32,
    // @@protoc_insertion_point(field:blobstream.v1.SegmentPartitionIndex.batch)
    pub batch: ::protobuf::MessageField<SegmentBatchMetadata>,
    // special fields
    // @@protoc_insertion_point(special_field:blobstream.v1.SegmentPartitionIndex.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SegmentPartitionIndex {
    fn default() -> &'a SegmentPartitionIndex {
        <SegmentPartitionIndex as ::protobuf::Message>::default_instance()
    }
}

impl SegmentPartitionIndex {
    pub fn new() -> SegmentPartitionIndex {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "virtual_partition_id",
            |m: &SegmentPartitionIndex| { &m.virtual_partition_id },
            |m: &mut SegmentPartitionIndex| { &mut m.virtual_partition_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, SegmentBatchMetadata>(
            "batch",
            |m: &SegmentPartitionIndex| { &m.batch },
            |m: &mut SegmentPartitionIndex| { &mut m.batch },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SegmentPartitionIndex>(
            "SegmentPartitionIndex",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SegmentPartitionIndex {
    const NAME: &'static str = "SegmentPartitionIndex";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.virtual_partition_id = is.read_uint32()?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.batch)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.virtual_partition_id != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.virtual_partition_id);
        }
        if let Some(v) = self.batch.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.virtual_partition_id != 0 {
            os.write_uint32(1, self.virtual_partition_id)?;
        }
        if let Some(v) = self.batch.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SegmentPartitionIndex {
        SegmentPartitionIndex::new()
    }

    fn clear(&mut self) {
        self.virtual_partition_id = 0;
        self.batch.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SegmentPartitionIndex {
        static instance: SegmentPartitionIndex = SegmentPartitionIndex {
            virtual_partition_id: 0,
            batch: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SegmentPartitionIndex {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SegmentPartitionIndex").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SegmentPartitionIndex {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SegmentPartitionIndex {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:blobstream.v1.SegmentBatchMetadata)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct SegmentBatchMetadata {
    // message fields
    // @@protoc_insertion_point(field:blobstream.v1.SegmentBatchMetadata.seq_start)
    pub seq_start: u64,
    // @@protoc_insertion_point(field:blobstream.v1.SegmentBatchMetadata.seq_end)
    pub seq_end: u64,
    // @@protoc_insertion_point(field:blobstream.v1.SegmentBatchMetadata.byte_start)
    pub byte_start: u64,
    // @@protoc_insertion_point(field:blobstream.v1.SegmentBatchMetadata.byte_end)
    pub byte_end: u64,
    // @@protoc_insertion_point(field:blobstream.v1.SegmentBatchMetadata.payload_bytes)
    pub payload_bytes: u64,
    // special fields
    // @@protoc_insertion_point(special_field:blobstream.v1.SegmentBatchMetadata.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a SegmentBatchMetadata {
    fn default() -> &'a SegmentBatchMetadata {
        <SegmentBatchMetadata as ::protobuf::Message>::default_instance()
    }
}

impl SegmentBatchMetadata {
    pub fn new() -> SegmentBatchMetadata {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "seq_start",
            |m: &SegmentBatchMetadata| { &m.seq_start },
            |m: &mut SegmentBatchMetadata| { &mut m.seq_start },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "seq_end",
            |m: &SegmentBatchMetadata| { &m.seq_end },
            |m: &mut SegmentBatchMetadata| { &mut m.seq_end },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "byte_start",
            |m: &SegmentBatchMetadata| { &m.byte_start },
            |m: &mut SegmentBatchMetadata| { &mut m.byte_start },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "byte_end",
            |m: &SegmentBatchMetadata| { &m.byte_end },
            |m: &mut SegmentBatchMetadata| { &mut m.byte_end },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "payload_bytes",
            |m: &SegmentBatchMetadata| { &m.payload_bytes },
            |m: &mut SegmentBatchMetadata| { &mut m.payload_bytes },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<SegmentBatchMetadata>(
            "SegmentBatchMetadata",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for SegmentBatchMetadata {
    const NAME: &'static str = "SegmentBatchMetadata";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.seq_start = is.read_uint64()?;
                },
                16 => {
                    self.seq_end = is.read_uint64()?;
                },
                24 => {
                    self.byte_start = is.read_uint64()?;
                },
                32 => {
                    self.byte_end = is.read_uint64()?;
                },
                40 => {
                    self.payload_bytes = is.read_uint64()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.seq_start != 0 {
            my_size += ::protobuf::rt::uint64_size(1, self.seq_start);
        }
        if self.seq_end != 0 {
            my_size += ::protobuf::rt::uint64_size(2, self.seq_end);
        }
        if self.byte_start != 0 {
            my_size += ::protobuf::rt::uint64_size(3, self.byte_start);
        }
        if self.byte_end != 0 {
            my_size += ::protobuf::rt::uint64_size(4, self.byte_end);
        }
        if self.payload_bytes != 0 {
            my_size += ::protobuf::rt::uint64_size(5, self.payload_bytes);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.seq_start != 0 {
            os.write_uint64(1, self.seq_start)?;
        }
        if self.seq_end != 0 {
            os.write_uint64(2, self.seq_end)?;
        }
        if self.byte_start != 0 {
            os.write_uint64(3, self.byte_start)?;
        }
        if self.byte_end != 0 {
            os.write_uint64(4, self.byte_end)?;
        }
        if self.payload_bytes != 0 {
            os.write_uint64(5, self.payload_bytes)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> SegmentBatchMetadata {
        SegmentBatchMetadata::new()
    }

    fn clear(&mut self) {
        self.seq_start = 0;
        self.seq_end = 0;
        self.byte_start = 0;
        self.byte_end = 0;
        self.payload_bytes = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static SegmentBatchMetadata {
        static instance: SegmentBatchMetadata = SegmentBatchMetadata {
            seq_start: 0,
            seq_end: 0,
            byte_start: 0,
            byte_end: 0,
            payload_bytes: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for SegmentBatchMetadata {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("SegmentBatchMetadata").unwrap()).clone()
    }
}

impl ::std::fmt::Display for SegmentBatchMetadata {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SegmentBatchMetadata {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:blobstream.v1.StoredSegmentCompressionCodec)
pub enum StoredSegmentCompressionCodec {
    // @@protoc_insertion_point(enum_value:blobstream.v1.StoredSegmentCompressionCodec.STORED_SEGMENT_COMPRESSION_CODEC_NONE)
    STORED_SEGMENT_COMPRESSION_CODEC_NONE = 0,
    // @@protoc_insertion_point(enum_value:blobstream.v1.StoredSegmentCompressionCodec.STORED_SEGMENT_COMPRESSION_CODEC_ZSTD)
    STORED_SEGMENT_COMPRESSION_CODEC_ZSTD = 1,
}

impl ::protobuf::Enum for StoredSegmentCompressionCodec {
    const NAME: &'static str = "StoredSegmentCompressionCodec";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<StoredSegmentCompressionCodec> {
        match value {
            0 => ::std::option::Option::Some(StoredSegmentCompressionCodec::STORED_SEGMENT_COMPRESSION_CODEC_NONE),
            1 => ::std::option::Option::Some(StoredSegmentCompressionCodec::STORED_SEGMENT_COMPRESSION_CODEC_ZSTD),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<StoredSegmentCompressionCodec> {
        match str {
            "STORED_SEGMENT_COMPRESSION_CODEC_NONE" => ::std::option::Option::Some(StoredSegmentCompressionCodec::STORED_SEGMENT_COMPRESSION_CODEC_NONE),
            "STORED_SEGMENT_COMPRESSION_CODEC_ZSTD" => ::std::option::Option::Some(StoredSegmentCompressionCodec::STORED_SEGMENT_COMPRESSION_CODEC_ZSTD),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [StoredSegmentCompressionCodec] = &[
        StoredSegmentCompressionCodec::STORED_SEGMENT_COMPRESSION_CODEC_NONE,
        StoredSegmentCompressionCodec::STORED_SEGMENT_COMPRESSION_CODEC_ZSTD,
    ];
}

impl ::protobuf::EnumFull for StoredSegmentCompressionCodec {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("StoredSegmentCompressionCodec").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for StoredSegmentCompressionCodec {
    fn default() -> Self {
        StoredSegmentCompressionCodec::STORED_SEGMENT_COMPRESSION_CODEC_NONE
    }
}

impl StoredSegmentCompressionCodec {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<StoredSegmentCompressionCodec>("StoredSegmentCompressionCodec")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1cblobstream/v1/metadata.proto\x12\rblobstream.v1\"\x9c\x02\n\x11Seg\
    mentMetadataV1\x12\x19\n\x08blob_key\x18\x01\x20\x01(\tR\x07blobKey\x12\
    \"\n\rcreated_ts_ms\x18\x02\x20\x01(\x03R\x0bcreatedTsMs\x127\n\x18metad\
    ata_published_ts_ms\x18\x03\x20\x01(\x03R\x15metadataPublishedTsMs\x12I\
    \n\x0bcompression\x18\x04\x20\x01(\x0b2'.blobstream.v1.StoredSegmentComp\
    ressionR\x0bcompression\x12D\n\npartitions\x18\x05\x20\x03(\x0b2$.blobst\
    ream.v1.SegmentPartitionIndexR\npartitions\"t\n\x18StoredSegmentCompress\
    ion\x12B\n\x05codec\x18\x01\x20\x01(\x0e2,.blobstream.v1.StoredSegmentCo\
    mpressionCodecR\x05codec\x12\x14\n\x05level\x18\x02\x20\x01(\x05R\x05lev\
    el\"\x84\x01\n\x15SegmentPartitionIndex\x120\n\x14virtual_partition_id\
    \x18\x01\x20\x01(\rR\x12virtualPartitionId\x129\n\x05batch\x18\x02\x20\
    \x01(\x0b2#.blobstream.v1.SegmentBatchMetadataR\x05batch\"\xab\x01\n\x14\
    SegmentBatchMetadata\x12\x1b\n\tseq_start\x18\x01\x20\x01(\x04R\x08seqSt\
    art\x12\x17\n\x07seq_end\x18\x02\x20\x01(\x04R\x06seqEnd\x12\x1d\n\nbyte\
    _start\x18\x03\x20\x01(\x04R\tbyteStart\x12\x19\n\x08byte_end\x18\x04\
    \x20\x01(\x04R\x07byteEnd\x12#\n\rpayload_bytes\x18\x05\x20\x01(\x04R\
    \x0cpayloadBytes*u\n\x1dStoredSegmentCompressionCodec\x12)\n%STORED_SEGM\
    ENT_COMPRESSION_CODEC_NONE\x10\0\x12)\n%STORED_SEGMENT_COMPRESSION_CODEC\
    _ZSTD\x10\x01b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(4);
            messages.push(SegmentMetadataV1::generated_message_descriptor_data());
            messages.push(StoredSegmentCompression::generated_message_descriptor_data());
            messages.push(SegmentPartitionIndex::generated_message_descriptor_data());
            messages.push(SegmentBatchMetadata::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(StoredSegmentCompressionCodec::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
