load("@crates//:defs.bzl", "all_crate_deps")
load("//tools/lint:linters.bzl", "rust_binary", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "blob-stream-broker",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/bin/**/*.rs"],
    ),
    crate_features = ["default"],
    crate_name = "blob_stream_broker",
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = all_crate_deps(normal = True),
)

rust_binary(
    name = "blob-stream-broker-bin",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["default"],
    crate_name = "blob_stream_broker",
    crate_root = "src/main.rs",
    edition = "2024",
    deps = all_crate_deps(normal = True) + [":blob-stream-broker"],
)
