[package]
edition = "2024"
license = "Apache-2.0"
name    = "blob-stream-broker"
publish = false
version = "0.1.0"

[lib]
doctest = true

[dependencies]
anyhow.workspace                  = true
async-trait.workspace             = true
aws-config.workspace              = true
aws-sdk-dynamodb.workspace        = true
aws-sdk-s3.workspace              = true
aws-types.workspace               = true
axum.workspace                    = true
bd-grpc.workspace                 = true
bd-log.workspace                  = true
bd-log-util.workspace             = true
bd-panic.workspace                = true
bd-pgv.workspace                  = true
bd-rt.workspace                   = true
bd-runtime-config.workspace       = true
bd-server-stats.workspace         = true
bd-shutdown.workspace             = true
bd-time.workspace                 = true
blob-stream-blob-store.path       = "../blob-stream-blob-store"
blob-stream-broker-discovery.path = "../blob-stream-broker-discovery"
blob-stream-metadata-store.path   = "../blob-stream-metadata-store"
blob-stream-proto.path            = "../blob-stream-proto"
blob-stream-types.path            = "../blob-stream-types"
bytes.workspace                   = true
clap.workspace                    = true
futures.workspace                 = true
hostname.workspace                = true
http.workspace                    = true
log.workspace                     = true
parking_lot.workspace             = true
prometheus.workspace              = true
protobuf.workspace                = true
protobuf-json-mapping.workspace   = true
serde.workspace                   = true
serde_json.workspace              = true
serde_yaml.workspace              = true
sonyflake.workspace               = true
thiserror.workspace               = true
tikv-jemalloc-ctl.workspace       = true
tikv-jemallocator.workspace       = true
time.workspace                    = true
tokio.workspace                   = true
uuid.workspace                    = true
zstd.workspace                    = true

[target.'cfg(target_os = "linux")'.dependencies]
cgroups-rs.workspace = true

[dev-dependencies]
blob-stream-test-utils.path = "../blob-stream-test-utils"
mockall.workspace           = true
