load("@crates//:defs.bzl", "all_crate_deps")
load("//tools/lint:linters.bzl", "rust_binary")
load("//tools/rust:tests.bzl", "rust_library_with_test")

package(default_visibility = ["//visibility:public"])

rust_library_with_test(
    name = "blob-stream-integration-tests",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/bin/**/*.rs"],
    ),
    crate_features = ["default"],
    crate_name = "blob_stream_integration_tests",
    crate_root = "src/lib.rs",
    edition = "2024",
    integration_test_deps = all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
    integration_test_itest_deps = [
        "dynamodb",
        "localstack",
    ],
    deps = all_crate_deps(normal = True),
)

rust_binary(
    name = "blob-stream-stress",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["default"],
    crate_name = "blob_stream_stress",
    crate_root = "src/bin/blob_stream_stress.rs",
    edition = "2024",
    deps = all_crate_deps(normal = True) + [":blob-stream-integration-tests"],
)
