load("@crates//:defs.bzl", "all_crate_deps")
load("//tools/lint:linters.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "blob-stream-runtime-config",
    srcs = ["src/lib.rs"],
    crate_features = ["default"],
    crate_name = "blob_stream_runtime_config",
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = all_crate_deps(normal = True),
)
