load("@crates//:defs.bzl", "all_crate_deps")
load("//tools/lint:linters.bzl", "rust_binary")
load("//tools/rust:tests.bzl", "rust_library_with_test")

package(default_visibility = ["//visibility:public"])

rust_library_with_test(
    name = "blob-stream-metadata-inspector",
    srcs = ["src/lib.rs", "src/lib_test.rs"],
    crate_name = "blob_stream_metadata_inspector",
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = all_crate_deps(normal = True),
)

rust_binary(
    name = "blob-stream-metadata-inspector-bin",
    srcs = ["src/main.rs"],
    crate_name = "blob_stream_metadata_inspector_bin",
    crate_root = "src/main.rs",
    edition = "2024",
    deps = all_crate_deps(normal = True) + [":blob-stream-metadata-inspector"],
)
