[package]
edition = "2024"
license = "Apache-2.0"
name    = "blob-stream-metadata-store"
publish = false
version = "0.1.0"

[lib]
doctest = true

[dependencies]
anyhow.workspace            = true
async-trait.workspace       = true
aws-config.workspace        = true
aws-sdk-dynamodb.workspace  = true
bd-backoff.workspace        = true
bd-log.workspace            = true
bd-server-stats.workspace   = true
blob-stream-blob-store.path = "../blob-stream-blob-store"
blob-stream-proto.path      = "../blob-stream-proto"
blob-stream-types.path      = "../blob-stream-types"
bytes.workspace             = true
log.workspace               = true
parking_lot.workspace       = true
prometheus.workspace        = true
protobuf.workspace          = true
serde.workspace             = true
serde_dynamo                = { workspace = true, features = ["aws-sdk-dynamodb+1"] }
time.workspace              = true
tokio.workspace             = true

[dev-dependencies]
mockall.workspace = true
uuid.workspace    = true
