[package]
edition = "2024"
license = "Apache-2.0"
name    = "blob-stream-blob-store"
publish = false
version = "0.1.0"

[lib]
doctest = true

[dependencies]
anyhow.workspace            = true
async-trait.workspace       = true
aws-config.workspace        = true
aws-sdk-s3.workspace        = true
bd-log.workspace            = true
bd-runtime-config.workspace = true
blob-stream-runtime-config  = { path = "../blob-stream-runtime-config" }
bytes.workspace             = true
log.workspace               = true
parking_lot.workspace       = true
serde.workspace             = true
serde_json.workspace        = true
thiserror.workspace         = true
tokio.workspace             = true
tracing.workspace           = true

[dev-dependencies]
bd-test-helpers-core.workspace = true
mockall.workspace              = true
